remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag

title: Crora Browser
email: crora@duck.com
description: Simple, Privacy Based, Ethical Hacking Browser
show_downloads: true

crora:
  exe_url: https://github.com/Crora-Browser/Software/releases/latest/download/Crora_Setup.exe
  zip_url: https://github.com/Crora-Browser/Software/releases/latest/download/Crora_Browser.zip
  
nav:
  - title: Crora Browser
    url: /
  - title: EULA | Crora Browser
    url: /EULA/
  - title: Privacy Policy | Crora Browser
    url: /privacy_policy/
  - title: Engine | Crora Browser
    url: /engine/
